server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8
    max-connections: 2000
    max-http-post-size: 0
spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 60000
  resources:
    add-mappings: false
  http:
    encoding:
      charset: UTF-8
      force: true
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 45Mb
      max-request-size: 45Mb
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.tys.pyx: debug
    org.springframework.cache: trace
    root: INFO
mapper:
  safe-delete: true
  safe-update: true